<?
$PERM["Shpola_Work_Place_Mobile.php"]["13"]="X";
$PERM["Shpola_Work_Place_Mobile.php"]["6"]="X";
$PERM["Shpola_Work_Place.php"]["13"]="X";
$PERM["Shpola_Work_Place.php"]["6"]="X";
$PERM["Shpola_Work_Hours.php"]["13"]="X";
$PERM["Shpola_Work_Hours.php"]["6"]="X";
$PERM["Shpola_Socials.php"]["13"]="X";
$PERM["Shpola_Socials.php"]["6"]="X";
$PERM["Shpola_Socials-Mobile.php"]["13"]="X";
$PERM["Shpola_Socials-Mobile.php"]["6"]="X";
$PERM["Shpola_Socials-Mobile.php"]["10"]="X";
$PERM["Shpola_Socials-Mobile.php"]["16"]="X";
$PERM["Shpola_Rezka.php"]["13"]="X";
$PERM["Shpola_Rezka.php"]["6"]="X";
$PERM["Shpola_Metaloprocat.php"]["13"]="X";
$PERM["Shpola_Metaloprocat.php"]["6"]="X";
$PERM["Shpola_Dostavka.php"]["13"]="X";
$PERM["Shpola_Dostavka.php"]["6"]="X";
$PERM["Shpola_BydMaterial.php"]["13"]="X";
$PERM["Shpola_BydMaterial.php"]["6"]="X";
$PERM["ShpolaH1Text.php"]["13"]="X";
$PERM["ShpolaH1Text.php"]["6"]="X";
$PERM["Artem.php"]["13"]="X";
$PERM["Artem.php"]["6"]="X";
$PERM[".access.php"]["13"]="X";
$PERM[".access.php"]["6"]="X";
?>